export type LocalDraftBase = Readonly<{ id: string; name: string; version: number; revision: Readonly<{ revision: number; lifecycle: "draft" | "review" | "published" | "archived" }>; audit: Readonly<{ owner: string; createdAt: string; updatedAt: string }> }>;
export type DraftWorkflowResult<T> = Readonly<{ records: readonly T[]; selectedId: string | null }>;

export function validateDraftName(name: string): string | null { const value = name.trim(); return value.length >= 2 && value.length <= 80 ? null : "Use a name from 2 to 80 characters."; }
export function draftCopyName(name: string, existingNames: readonly string[]): string { const taken = new Set(existingNames.map((value) => value.toLowerCase())); const base = `${name} - Copy`; if (!taken.has(base.toLowerCase())) return base; let suffix = 2; while (taken.has(`${base} ${suffix}`.toLowerCase())) suffix += 1; return `${base} ${suffix}`; }
export function insertDraft<T>(records: readonly T[], draft: T): DraftWorkflowResult<T> { return { records: [draft, ...records], selectedId: (draft as LocalDraftBase).id }; }
export function saveDraft<T extends LocalDraftBase>(record: T, name: string): T | null { if (validateDraftName(name)) return null; return { ...record, name: name.trim(), revision: { ...record.revision, revision: 1, lifecycle: "draft" }, audit: { ...record.audit, updatedAt: "2026-08-04T00:00:00Z" } }; }
export function duplicateDraft<T extends LocalDraftBase>(record: T, records: readonly T[]): T { const name = draftCopyName(record.name, records.map((item) => item.name)); const id = draftCopyName(record.id, records.map((item) => item.id)).replace(/ /g, "-").toLowerCase(); return { ...record, id, name, revision: { ...record.revision, revision: 1, lifecycle: "draft" }, audit: { ...record.audit, updatedAt: "2026-08-04T00:00:00Z" } }; }
export function removeDraft<T extends LocalDraftBase>(records: readonly T[], id: string, fallbackId: string | null = null): DraftWorkflowResult<T> { const remaining = records.filter((record) => record.id !== id); return { records: remaining, selectedId: remaining.some((record) => record.id === fallbackId) ? fallbackId : remaining[0] ? remaining[0].id : null }; }
